### ISSUE TITLE
Instalação via NPM

### ISSUE THREAD

**Issue by Diego-Brocanelli** [ion-project/ion-design#5]
Olá, 

Há pretensão de que o projeto possa ser portado para que o mesmo seja instalado via NPM?

Achei o projeto muito bacana, porém acredito que isso irá agregar valor ao projeto, pois facilitaria o consumo do projeto.

**Comment by gabrielcursino** [comment]
Olá Diego, tudo bem?

Sim, futuramente quero que o projeto esteja disponível via npm também, assim como em cdn’s para uso direto, sem necessidade de download.
Eu ainda não procurei como adaptar meu projeto para o npm, mas com certeza vai ser uma das coisas que eu vou fazer futuramente.

**Comment by Diego-Brocanelli** [comment]
Olá, @gabrielcursino .

Show de bola!

**Comment by gabrielcursino** [comment]
O projeto agora pode ser instalado via npm também: `npm install ion-design`!
